server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://47.119.201.65:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 47.119.201.65
    virtual-host: /Liangbin Chen
    username: Liangbin Chen
    password: 243533Clb
