server:
  port: 8093
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 47.119.201.65
  rabbitmq:
    host: 47.119.201.65
    virtual-host: /Liangbin Chen
    username: Liangbin Chen
    password: 243533Clb

gmall:
  jwt:
    pubKeyPath: \\Users\\chenliangbin\\Desktop\\GitHubProject\\RSA\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    expire: 3000 # 过期时间,单位分钟

alipay:
  app_id: 2021000117682785
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwcUCxSpP107JiSZTrfYqbVP46Yd2lDEGsH6gpkvUK2zMuvj3SPGTO4qHyCadTBuWlmx5yxJOtyKLlIKbG/09uRpwzvnFFtGA05blvGV0kAsSjla0m3sFCoYiBmX73QsMsSge+Q7xhXF4R5DtPzyOZT88iKG3JZzOaWp9AUS9LTn3il+7+ahAUr7imJKLpm0iw1dDN9MJSHXp4zRG3OIgqdxomuGzvhY0WAhbEml1szGMPo29zsL8wIF7m8oFhlQoMuHbBJfYBmt47s3g29NXGrDdQO/3IqNJkxHR/ndZETaIByVCqcX2rBLbbl68uxkcOV+bm9436OAgdC91YuNWNAgMBAAECggEAXqr1Neq4xm3mSRwHve4m3z7UBMkbngGcftihZmUF+uQvawYBr3pd8C7jCzUoxMBvmNJInPVh8x0yYVOKiDzWBmn2R0EID4k/EUKsorJuKfMeRFL7i157PN/kmPydhdcZVvsFeo1nVqmzg0/8js6p4AlVLpOYjDZGFqxGw8CLapB3e2mlbpqaUOrrUNRvvlCsaPFh/3UixB+zDvhQac5u1JOWicCXF5BEuSV0hKz5EvqZXLmG5sY1WLB0YhaApEQaK4atjPSCu3p9/pxzjM7Ura1wPhSzTPDIzjMp22l1DFQ66/uXxpaFKsz2j/umOb72jr+oMI7ytfcs5JO2330nQQKBgQDcnHIQc0wbmQmTJCRnF0duTlqqY2UPf8fkMVP9Cz021gqw+9zVgBYJZHpLNRDPI/EgI3ttJ/1pDLJ3HoRR0fVkVENQJHXnKLrp3SAJHfTTwlMayKKUCMA3xPnqsJHkeNBsXsYHd2E04znqWRn3FkUOt6iRllA4VdiJ8KIWZssVPQKBgQDMvvya8XqZMqO/492W5qTg39JTZUZY2Up9ivlUQfze/ciud4TtUiEjmMLkd0aI0T/fsETIo+MQ1lMC2s6SnL6mvDckrZtctf4t5BZqA5moITToHUyB9aMfNRF8Nk1Pyx2jXXeGt6T7Bg2UQwxejwkGrIiYRWln2ddJB0z5AOHmkQKBgQCn2/oGflQoo5dfeB6iulnFmqTuBNb+phGolcf8QDMBqHdWFy3+3Yjm+Kb81pHFqulrtNPTSJxO9DRO4s93mjQHdP4K2tNDYgBmtbQMe9ivz6qANK1PyiDHzn8CjftURoEAFFTFlZZHMaX9pHJXSYCeJCyFKkQ7uUYcHxaVyP05WQKBgH5wk168MZHaC/W8qmM+HCQjFKgbqs3DopTU9hRqi9bJstzLQnOsfHqXJAQjBJQJZQCmwlOFofwL30esCFXSJoqhQQyNiZw/Z7C/YnglsQZ7O0j8jvrSzuG+zAWBI01bifoRBndTgbbjjg85OLJMcq6EbfZbJzTS+nhG4eoD+X2BAoGBAMQyPdvpH+yAHSIUe4EEqxFpUmldiJwbvwEffEBdDLrugV+10RpXVcGabYJ5cJd+Lc16YpEyecuxSCc/F2w205AGomfhhOMU+z/bwBwLzs/VAdwIbcycuGAyMAzXjOOurFlaePIeLCRL5XPMianABSsz8ZBIq3JzS4g49/sha7Ao
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnpwpUW9H+A/X7cnNyocZGLxn4NqTBvGnmjKXFzlkBXMJc6cotPi2Yl/Bu07EJaEq8xQ1cJlmopvwFsxEoahloYQcomiCW6B3gdIMyW2P/dYkC6gWp7NsVxnoAvVOWnDoflCVSg85WFVQMIV6HHu0+9RQcU7pgs5tqA9hMmHRAzb4a0VsjZ1N2ytQwTBLxn8QdSVpnrhYL/N6IVMPPYuincsYhDvyxpUDGl5dp9rt7oiZBG+SWQAbBhYHg1Bxc8GhTjU84chIVilIf0ExGAkGtK9v+8Y+0ndFWr0KZor8Q1upbpSAoY5zdeHYyqZYh6dzl32ZMC5BN3bBU6y2IZF/SQIDAQAB
  notify_url: http://ktr37sgryb.52http.tech/api/order/pay/success #http://9glldacce2.52http.net/api/order/pay/alipay/success # 域名是哲西云提供的域名，路径是订单支付成功回调的路径
  return_url: http://www.baidu.com #http://localhost:2000/pay/success.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
