server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    host: 47.119.201.65
  rabbitmq:
    host: 47.119.201.65
    virtual-host: /Liangbin Chen
    username: Liangbin Chen
    password: 243533Clb
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/oms/**/*.xml
