server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 47.119.201.65
    port: 5672
    virtual-host: /Liangbin Chen
    username: Liangbin Chen
    password: 243533Clb
item:
  rabbitmq:
    exchange: GMALL-PMS-EXCHANGE
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/pms/**/*.xml

seata:
  enabled: true
  application-id: pms-service
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  registry:
    type: file
    file:
      name: file.conf
  log:
    exception-rate: 100